---
spring:
  config.activate.on-profile: cloud
cds:
  data-source.auto-config.enabled: true
  security:
    mock.users:
        infouser:
          password: infouser-pass
          privileged: true
          roles:
          - Infouser
        user:
          password: user-pass
          privileged: true
          roles:
          - User
        admin:
          password: admin-pass
          privileged: true
          roles:
          - Admin
    authentication:
      mode: "any"
  remote.services:
    "publicOdata":
      type: "odata-v4"
      http:
        service: "TripPinRESTierService"
      destination:
        name: "odata-v4-destination"
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
